<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="NSubstitute" Version="5.3.0" />
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Logly.Kafka\Logly.Kafka.csproj" />
      <ProjectReference Include="..\..\src\Logly.LogsAnalyzer\Logly.LogsAnalyzer.csproj" />
      <ProjectReference Include="..\..\src\Logly.LogsGenerator\Logly.LogsGenerator.csproj" />
      <ProjectReference Include="..\..\src\Logly.ParsedLogsHandler\Logly.ParsedLogsHandler.csproj" />
      <ProjectReference Include="..\..\src\Logly.RawLogsHandler\Logly.RawLogsHandler.csproj" />
      <ProjectReference Include="..\..\src\Logly.Serialization\Logly.Serialization.csproj" />
    </ItemGroup>

</Project>