<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Logly.Kafka\Logly.Kafka.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Integration\Models\Messages\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="ClickHouse.Client" Version="7.14.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

</Project>
